name: Deploy App

'on':
  push:
    branches:
      - main
# on:
#   pull_request:
#     branches:
#       - main

jobs:
  tests:
    name: Deploy Process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r deploy/app.zip ./ -x ".git/*" -x "node_modules/*"

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: deploy/app.zip
          retention-days: 1

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ${{ vars.PROTOCOL_FTP }}
          local-dir: ./deploy/
          log-level: verbose
          timeout: 60000

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/public_html
            unzip -o app.zip -d /home/${{ secrets.SSH_USERNAME }}/public_html/
            rm -rf app.zip
            sed -i~ '/^VERSION=/s/=.*/="${{ vars.VERSION }}"/' .env
            sed -i~ '/^HASH_VERSION=/s/=.*/="${{ github.sha }}"/' .env
            # sed -i~ '/^HASH_VERSION=/s/=.*/="${{ vars.HASH_VERSION }}"/' .env
